djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home
from menu.views import menu, menu_dish, menu_category
from events.views import events, events_year, events_year_month
from gallery.views import gallery
from contacts.views import contacts


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),

    path('menu/', include('menu.urls')),
    path('events/', include('events.urls')),
    path('gallery', gallery, name='gallery'),
    path('contacts', contacts, name='contacts'),
]

events/urls.py
from  django.urls import path
from .views import events,events_year,events_year_month, future_events

app_name = 'events'

urlpatterns = [
    path('', events, name='events'),
    path('future', future_events, name = 'future_events'),
    path('<int:year>', events_year, name='events_year'),
    path('<int:year>/<int:month>', events_year_month, name='events_year_month'),
]

menu/urls.py
from django.urls import path
from .views import menu, menu_dish, menu_category

app_name = 'menu'

urlpatterns = [
    path('', menu, name='menu'),
    path('<int:category>', menu_category, name='menu_category'),
    path('<int:category>/<int:dish>', menu_dish, name='menu_dish'),
]

contacts/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

# Create your models here.


class MenuBaseMixin(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)
    position = models.PositiveSmallIntegerField(unique=True)
    is_visible = models.BooleanField(default=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class MenuCategory(MenuBaseMixin):
   pass


class MenuDish(MenuBaseMixin):
    category = models.ForeignKey(MenuCategory, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()
    ingredients = models.TextField()
    photo = models.ImageField(upload_to='menu_dishes', blank=True)

contacts/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def contacts(request):
     return HttpResponse('<h1>This future contact page</h1>')

events/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def events(request):
    return HttpResponse('<h1>This events page</h1>')


def events_year(request, year):
    if year < 2024:
        return HttpResponse('<h1>We were closed</h1>')
    return HttpResponse(f'<h1>This events {year} page</h1>')

def events_year_month(request, year, month):
    if year < 2024:
        return HttpResponse('<h1>We were closed</h1>')
    return HttpResponse(f'<h1>This events {year}, {month} month </h1>')


def future_events(request):
    return HttpResponse('<h1>This future events page</h1>')

gallery/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def gallery(request):
    return HttpResponse('<h1>This future gallery page</h1>')

home/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'layouts/welcome.html')

menu/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def menu(request):
    return HttpResponse('<h1>This future menu page</h1>')


def menu_category(request, category:int):
    return HttpResponse(f'<h1>This future menu_category {category} page</h1>')


def menu_dish(request, category:int, dish:int):
    return HttpResponse(f'<h1>This future menu_category {category}, dish - {dish} page</h1>')

templates/layouts/welcome.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'menu:menu' %}">Menu</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:future_events' %}">Events</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacts' %}">Contacts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gallery' %}">Gallery</a>
            </li>
          </ul>
        </div>
      </div>
        </nav>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>